version: "3.8"

services:
  mysqldb:
    image: mysql:5.7 # official Docker image
    env_file: .env # specify my .env path that we will create later
    environment: # provide setting using environment variables
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=batch
    ports: # specify ports will be used
      - 3307:3306
    volumes: #map volume folders
      - db:/var/lib/mysql

  app:
    depends_on: # dependency order, mysqldb is started before app
      - mysqldb
    build: . # configuration options that are applied at build time that we defined in the Dockerfile with relative path
    restart: on-failure
    env_file: .env
    ports:
      - 8080:8080
    environment: # environmental variables that Spring Boot application uses
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/batch?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "admin",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true # stdin_open and tty: keep open the terminal after building container
    tty: true # stdin_open and tty: keep open the terminal after building container

volumes:
  db: